import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';import'./styles.css';
type Any=Record<string,any>; type Page='Dashboard'|'Acquire'|'Preprocess'|'SR Engine'|'Validate'|'Uncertainty'|'Analysis'|'AI Analyst'|'Architecture'|'Report'|'About';
const api=async(path:string,body:Any={})=>{const r=await fetch('/api'+path,{method:path==='/health'?'GET':'POST',headers:{'Content-Type':'application/json'},body:path==='/health'?undefined:JSON.stringify(body)});if(!r.ok)throw new Error('Local API unavailable');return r.json()};
const nav:Page[]=['Dashboard','Acquire','Preprocess','SR Engine','Validate','Uncertainty','Analysis','AI Analyst','Architecture'];
const workflow:[Page,string,string,string][]=[['Acquire','Acquire','Select one consistent Sentinel-2 L2A demonstration scene.','A known scene anchors every stage of the story.'],['Preprocess','Quality','Review scene quality and cloud/shadow conditions.','Input quality constrains responsible interpretation.'],['Preprocess','Preprocess','Extract, align and normalize B02/B03/B04/B08.','The model needs consistent multispectral pixels.'],['SR Engine','Reconstruct','Create a source-derived prototype SR preview.','Fine-scale detail is model-reconstructed, not directly observed.'],['Validate','Validate','Review spatial, spectral and geospatial checks.','Scientific validation frames usefulness.'],['Uncertainty','Uncertainty','Visualize where reconstruction is less reliable.','Not every fine-scale feature is equally certain.'],['Analysis','Analyze','Apply the selected scene to EO interpretation.','Downstream use remains uncertainty-aware.'],['AI Analyst','Explain','Nemotron summarizes the current scene context.','Reasoning is separate from image reconstruction.']];
const names:Record<string,string>={urban:'Bengaluru Urban Edge',agriculture:'Punjab Agricultural Mosaic',mixed:'Nashik Mixed Peri-Urban',disaster:'Assam Flood / Change Assessment'};
function Chip({children}:{children:React.ReactNode}){return <span className="chip">{children}</span>}function Badge({children}:{children:React.ReactNode}){return <span className="badge">{children}</span>}
function App(){
 const [page,setPage]=useState<Page>('Dashboard');const [scene,setScene]=useState(()=>localStorage.getItem('terrasr-scene')||'urban');const [data,setData]=useState<Any>({});const [health,setHealth]=useState<Any>({data:'demo',nemotron:'demo',pipeline:'ready'});const [help,setHelp]=useState(false);const [notes,setNotes]=useState(false);const [judge,setJudge]=useState(false);const [auto,setAuto]=useState(false);const [step,setStep]=useState(0);const [slider,setSlider]=useState(50);const [message,setMessage]=useState('');
 const route:Record<string,string>={'Dashboard':'/scenes/preview','Acquire':'/scenes/search','Preprocess':'/preprocess','SR Engine':'/sr/preview','Validate':'/validation','Uncertainty':'/uncertainty','Analysis':'/agriculture','AI Analyst':'/nemotron/analyze','Report':'/report'};
 const load=async()=>{try{if(route[page])setData(await api(route[page],{scene_id:scene,prompt:'Analyze Scene'}));}catch{setMessage('Local API unavailable. Start run.bat and refresh.')}};
 useEffect(()=>{api('/health').then(setHealth).catch(()=>{});},[]);useEffect(()=>{localStorage.setItem('terrasr-scene',scene);load()},[page,scene]);
 useEffect(()=>{if(!judge||!auto)return;const id=setInterval(()=>setStep(i=>{const next=i+1;if(next>=workflow.length){setAuto(false);return i}setPage(workflow[next][0]);return next}),6000);return()=>clearInterval(id)},[judge,auto]);
 const selected=(s:string)=>{setScene(s);setMessage(`✓ ${names[s]} selected. Continue to preprocessing.`)};
 const next=()=>{const n=Math.min(step+1,workflow.length-1);setStep(n);setPage(workflow[n][0])}; const restart=()=>{setStep(0);setAuto(false);setPage('Acquire')};
 const current=data.scene||data.metadata||{}; const observed=data.observed;const sr=data.sr_preview;
 const download=(kind:'json'|'csv')=>{const text=kind==='json'?JSON.stringify({scene:current,report:data},null,2):'field,value\nScene,"'+(current.name||names[scene])+'"\nStatus,Prototype Demonstration\nTarget,Sub-4 m model-reconstructed target\n';const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/'+kind}));a.download=`TerraSR_${scene}_report.${kind}`;a.click();URL.revokeObjectURL(a.href)};
 return <div className="shell"><header className="top"><button className="wordmark" onClick={()=>setPage('Dashboard')}><b>Terra<span>SR</span></b><small>Multispectral Earth Observation Super-Resolution Platform</small></button><div className="topright"><div className="statuses"><Chip>DATA · {health.data?.toUpperCase()}</Chip><Chip>SR · PROTOTYPE</Chip><Chip>AI · {health.nemotron?.toUpperCase()}</Chip><Chip>PIPELINE · {health.pipeline?.toUpperCase()}</Chip></div><button className="minor" onClick={()=>setHelp(true)}>How it works</button><button className="primary" onClick={()=>{setJudge(true);setStep(0);setPage('Acquire')}}>JUDGE MODE</button></div></header>
 <div className="navrow"><nav>{nav.map(x=><button key={x} className={page===x?'current':''} onClick={()=>setPage(x)}>{x}</button>)}</nav><button className="scenechip" onClick={()=>setPage('Acquire')}><b>CURRENT SCENE</b> {names[scene]} · 10 m · L2A · Cloud {(current.cloud_cover??({urban:4.2,agriculture:2.1,mixed:7.8,disaster:9.5}as Any)[scene])}%</button></div>
 <main>{message&&<div className="notice">{message}<button onClick={()=>setMessage('')}>×</button></div>}
 {page==='Dashboard'&&<Dashboard s={current} observed={observed} sr={sr} go={setPage}/>} {page==='Acquire'&&<Acquire data={data} selected={selected} chosen={scene} refresh={load}/>} {page==='Preprocess'&&<Preprocess data={data}/>} {page==='SR Engine'&&<SR data={data} slider={slider} setSlider={setSlider}/>} {page==='Validate'&&<Validate data={data}/>} {page==='Uncertainty'&&<Uncertainty data={data}/>} {page==='Analysis'&&<Analysis scene={scene} data={data}/>} {page==='AI Analyst'&&<Analyst scene={scene} data={data} setData={setData} go={setPage}/>} {page==='Architecture'&&<Architecture/>} {page==='Report'&&<Report data={data} download={download}/>} {page==='About'&&<About/>}
 </main><footer><span>AI-assisted spatial reconstruction for Earth observation</span><button onClick={()=>setNotes(true)}>Presenter notes</button><button onClick={()=>setPage('About')}>About TerraSR</button><span>Prototype for SIH 2026 • NTRO Problem Statement SIH26142</span></footer>
 {help&&<Modal title="How TerraSR works" close={()=>setHelp(false)}><ol>{['We acquire 10 m Sentinel-2 L2A imagery.','We quality-control and align multispectral bands.','We prepare the input for super-resolution.','SwinIR reconstructs fine-scale spatial detail.','We evaluate spatial and spectral fidelity.','We quantify uncertainty.','We use the result for downstream EO interpretation.','Nemotron helps interpret and orchestrate the workflow.'].map(x=><li key={x}>{x}</li>)}</ol></Modal>}
 {notes&&<Modal title="Presenter notes" close={()=>setNotes(false)}><p>First, we select a Sentinel-2 L2A scene at 10 m.</p><p>Next, the system performs cloud masking, band extraction, alignment and normalization.</p><p>We then prepare the B02, B03, B04 and B08 multispectral input.</p><p>Our production model is multispectral SwinIR, which reconstructs a sub-4 m target product.</p><p>We do not treat reconstructed detail as direct observation.</p><p>So we evaluate spatial and spectral fidelity and generate uncertainty.</p><p>Finally, the reconstructed product can support agriculture, urban, disaster and change-analysis workflows. Nemotron acts as the reasoning and orchestration layer.</p></Modal>}
 {judge&&<Modal title="TerraSR Judge Mode" close={()=>{setJudge(false);setAuto(false)}} wide><div className="timeline">{workflow.map((x,i)=><button key={x[1]} className={i===step?'active':i<step?'done':''} onClick={()=>{setStep(i);setPage(x[0])}}><b>{String(i+1).padStart(2,'0')}</b>{x[1]}</button>)}</div><div className="judgecopy"><Badge>STEP {String(step+1).padStart(2,'0')} — {workflow[step][1].toUpperCase()}</Badge><h2>{workflow[step][2]}</h2><p><b>Why it matters:</b> {workflow[step][3]}</p><p><b>Result:</b> {names[scene]} remains the single scene used throughout this guided demonstration.</p></div><div className="actions"><button className="minor" onClick={restart}>RESTART</button><button className="minor" onClick={()=>setAuto(!auto)}>{auto?'PAUSE':'AUTO RUN · ~48 SEC'}</button><button className="primary" onClick={next}>NEXT STEP</button></div></Modal>}
 </div>}
function Head({eyebrow,title,subtitle}:{eyebrow:string,title:string,subtitle:string}){return <section className="head"><span>{eyebrow}</span><h1>{title}</h1><p>{subtitle}</p></section>}
function Panel({children,className=''}:{children:React.ReactNode,className?:string}){return <section className={'panel '+className}>{children}</section>}
function Dashboard({s,observed,sr,go}:{s:Any,observed:string,sr:string,go:(p:Page)=>void}){return <><Head eyebrow="TERRASR / DEMONSTRATION MODE" title="10 m → Sub-4 m Model-Reconstructed Target" subtitle="From 10 m satellite observations to uncertainty-aware fine-scale reconstruction."/><section className="dashboard"><Panel className="scene"><span className="label">SELECTED SATELLITE SCENE</span>{observed&&<img src={observed}/>}<h2>{s.name||'Loading scene…'}</h2><p>{s.location} · {s.date}</p><Badge>DEMO DATA</Badge></Panel><Panel className="transition"><span className="label">RECONSTRUCTION PREVIEW</span><div className="twins">{observed&&<figure><img src={observed}/><figcaption>10 m OBSERVED</figcaption></figure>}{sr&&<figure><img src={sr}/><figcaption>SUB-4 m MODEL-RECONSTRUCTED TARGET</figcaption></figure>}</div><p>PROTOTYPE SR PREVIEW · source-derived visual enhancement; trained SwinIR weights are not run.</p></Panel><Panel className="process"><span className="label">PROCESSING STATUS</span><Status t="Scene acquired"/><Status t="Quality-aware preprocessing"/><Status t="Prototype SR preview"/><Status t="Validation & uncertainty"/><button className="primary full" onClick={()=>go('Preprocess')}>RUN ANALYSIS</button><button className="minor full" onClick={()=>go('Acquire')}>CHANGE SCENE</button></Panel></section><section className="fourcards"><Info t="INPUT" a="Sentinel-2 L2A" b="10 m observed"/><Info t="TARGET" a="Sub-4 m" b="Model-reconstructed"/><Info t="MODEL" a="Multispectral SwinIR" b="Production integration point"/><Info t="RELIABILITY" a="Validation + uncertainty" b="Independent reference required"/></section></>}
function Status({t}:{t:string}){return <div className="statusline"><i/> {t}<b>READY</b></div>}function Info({t,a,b}:{t:string,a:string,b:string}){return <Panel><span className="label">{t}</span><h3>{a}</h3><p>{b}</p></Panel>}
function Acquire({data,selected,chosen,refresh}:{data:Any,selected:(s:string)=>void,chosen:string,refresh:()=>void}){return <><Head eyebrow="01 / ACQUIRE" title="Scene Acquisition" subtitle="Select the Earth observation scene to analyze."/><section className="acquire"><Panel className="controls"><Badge>{data.source||'DEMO DATA'}</Badge><h3>AOI / scene controls</h3><label>Location<input value="Demonstration AOI" readOnly/></label><label>Date range<input value="2025 demonstration scenes" readOnly/></label><label>Maximum cloud cover<input value="10%" readOnly/></label><button className="primary full" onClick={refresh}>SEARCH SCENES</button><button className="minor full" onClick={()=>selected(chosen)}>USE DEMO SCENE</button><p>{data.notice}</p></Panel><Panel className="demomap"><span className="label">SPATIAL CONTEXT</span><div className="mapgrid"><b>DEMO AOI</b><span>Sentinel-2 L2A catalogue contract</span></div><p>Offline demonstration dataset active. Live metadata is never mixed with demo imagery.</p></Panel><div className="results">{(data.scenes||[]).map((s:Any)=><Panel key={s.id} className={chosen===s.id?'selected':''}><Badge>{s.mode}</Badge><h3>{s.name}</h3><p>{s.location}</p><p>{s.date} · Cloud {s.cloud_cover}% · {s.resolution} · {s.crs}</p><button className={chosen===s.id?'minor':'primary'} onClick={()=>selected(s.id)}>{chosen===s.id?'✓ SCENE SELECTED':'SELECT SCENE'}</button></Panel>)}</div></section></>}
function Preprocess({data}:{data:Any}){return <><Head eyebrow="03 / PREPROCESS" title="Preparing the Multispectral Input" subtitle="Quality-controlled B02/B03/B04/B08 for a consistent reconstruction workflow."/><section className="pretop"><Panel><span className="label">INPUT</span><h3>{data.input||'Sentinel-2 L2A · 10 m'}</h3></Panel><Panel><span className="label">SELECTED BANDS</span><div className="bands">{(data.bands||['B02','B03','B04','B08']).map((x:string)=><Badge key={x}>{x}</Badge>)}</div></Panel><details><summary>Why these bands?</summary><p><b>B02</b> Blue · <b>B03</b> Green · <b>B04</b> Red · <b>B08</b> Near Infrared. These bands provide the multispectral signal used by the prototype SR pipeline.</p></details></section><section className="steps">{(data.steps||[]).map((x:Any)=><Panel key={x.id}><Badge>{x.id} · {x.status}</Badge><h3>{x.name}</h3><p><b>Purpose:</b> {x.purpose}</p><p><b>Output:</b> {x.output}</p></Panel>)}</section><Panel className="console"><span className="label">CONCISE PROCESSING LOG</span>{(data.logs||[]).map((x:string)=><p key={x}>✓ {x}</p>)}</Panel></>}
function SR({data,slider,setSlider}:{data:Any,slider:number,setSlider:(n:number)=>void}){return <><Head eyebrow="04 / RECONSTRUCT" title="Multispectral Super-Resolution" subtitle="Reconstructing fine-scale spatial detail from multispectral Sentinel-2 observations."/><section className="strip"><Info t="INPUT" a="10 m" b="Observed"/><Info t="BANDS" a="B02 / B03 / B04 / B08" b="Multispectral input"/><Info t="MODEL" a="Multispectral SwinIR" b="Production engine"/><Info t="TARGET" a="Sub-4 m" b="Model-reconstructed"/></section><Panel className="viewer"><div className="base">{data.observed&&<img src={data.observed}/>}<b>ORIGINAL · 10 m OBSERVED</b></div><div className="reveal" style={{width:slider+'%'}}>{data.sr_preview&&<img src={data.sr_preview}/>}<b>SR PREVIEW · SUB-4 m MODEL-RECONSTRUCTED TARGET</b></div><input aria-label="Compare original and SR preview" type="range" min="0" max="100" value={slider} onChange={e=>setSlider(+e.target.value)}/></Panel><section className="explain"><Panel><Badge>PROTOTYPE SR PREVIEW</Badge><p>{data.real_swinir}</p></Panel><Panel><span className="label">MODEL PIPELINE</span><p>B02/B03/B04/B08 → Feature extraction → Swin Transformer blocks → Deep feature reconstruction → Upsampling → SR output</p><p><b>SwinIR</b> is the super-resolution engine. <b>Nemotron</b> is the reasoning/orchestration layer.</p></Panel></section></>}
function Validate({data}:{data:Any}){const groups=['Spatial fidelity','Spectral fidelity'];return <><Head eyebrow="05 / VALIDATE" title="Scientific Validation" subtitle="How do we know the reconstruction is useful?"/><Badge>ALL VALUES · DEMO / ILLUSTRATIVE</Badge>{groups.map(g=><section className="metricgroup" key={g}><h2>{g}</h2><div>{(data.metrics||[]).filter((x:Any)=>x.group===g).map((x:Any)=><Panel key={x.name}><span className="label" title={x.help}>{x.name} ⓘ</span><h2>{x.value}</h2><Badge>DEMO VALUE</Badge><p>{x.help}</p></Panel>)}</div></section>)}<Panel><span className="label">GEOSPATIAL CONSISTENCY</span><div className="tags">{(data.geospatial||[]).map((x:string)=><Badge key={x}>{x}</Badge>)}</div></Panel></>}
function Uncertainty({data}:{data:Any}){return <><Head eyebrow="06 / UNCERTAINTY" title="Reconstruction Uncertainty" subtitle="Not every reconstructed detail is equally reliable."/><section className="uncert"><Panel className="uncimage">{data.uncertainty_image&&<img src={data.uncertainty_image}/>}<div><Badge>PROTOTYPE VISUALIZATION</Badge><p>LOW · MEDIUM · HIGH</p></div></Panel><Panel><h3>{data.mean}</h3><p>Mean uncertainty</p><h3>{data.p95}</h3><p>P95 uncertainty</p><h3>{data.region}</h3><p>{(data.focus||[]).join(' · ')}</p></Panel></section><Panel className="warning"><b>{data.note}</b></Panel></>}
function Analysis({scene,data}:{scene:string,data:Any}){const cards=[['AGRICULTURE','SR preview → NDVI → vegetation interpretation',scene==='agriculture'?data.result:'Vegetation-focused screening with B08 and B04.',scene==='agriculture'?data.uncertainty:'DEMO ANALYTICS'],['URBAN','SR preview → feature visibility → urban interpretation',scene==='urban'?data.result:'Improved visual interpretability; not guaranteed extraction.',scene==='urban'?data.uncertainty:'DEMO ANALYTICS'],['DISASTER','Pre-event + Post-event → change → potential regions',scene==='disaster'?'Pre/post context supports qualitative change screening.':'DEMO ANALYSIS','Boundary uncertainty requires reference validation.'],['CHANGE DETECTION','Scene A + Scene B → co-registration → difference map','Potential change areas are illustrative.','DEMO ANALYSIS']];return <><Head eyebrow="07 / ANALYZE" title="Downstream Earth Observation Applications" subtitle="Application outputs remain explicitly uncertainty-aware and illustrative."/><section className="applications">{cards.map(x=><Panel key={x[0]}><Badge>{x[0]}</Badge><h3>{x[1]}</h3><p><b>Analysis:</b> {x[2]}</p><p><b>Uncertainty:</b> {x[3]}</p>{x[0]==='AGRICULTURE'&&scene==='agriculture'&&<p><b>NDVI:</b> {data.ndvi} · {data.formula}</p>}</Panel>)}</section></>}
function Analyst({scene,data,setData,go}:{scene:string,data:Any,setData:(d:Any)=>void,go:(p:Page)=>void}){const ask=async(prompt:string)=>setData(await api('/nemotron/analyze',{scene_id:scene,prompt}));return <><Head eyebrow="08 / EXPLAIN" title="TerraSR AI Analyst" subtitle="NVIDIA Nemotron 3 Ultra · Reasoning and orchestration layer"/><section className="context">{['SCENE','PROCESSING','SR','VALIDATION','UNCERTAINTY','APPLICATION'].map(x=><Badge key={x}>{x}</Badge>)}</section><Panel className="analyst"><Badge>{data.mode||'DEMO ANALYST'}</Badge><h2>{data.model||'NVIDIA Nemotron 3 Ultra'}</h2><p>{data.response||'Loading selected-scene analysis…'}</p><div className="actiongrid">{['Analyze Scene','Explain Validation','Explain Uncertainty','Recommend Application','Generate Report'].map(x=><button key={x} className="minor" onClick={()=>ask(x)}>{x}</button>)}<button className="primary" onClick={()=>go('Report')}>VIEW SCENE REPORT</button></div></Panel><section className="roles"><Panel><span className="label">SWINIR</span><h3>Image reconstruction</h3></Panel><Panel><span className="label">NEMOTRON</span><h3>Reasoning + orchestration + explanation</h3></Panel></section></>}
function Architecture(){let nodes=['DATA SOURCE\nCopernicus / Sentinel-2 L2A','PREPROCESSING\nCloud mask · Alignment · Normalization','MULTISPECTRAL INPUT\nB02 / B03 / B04 / B08','SWINIR\nSpatial reconstruction','SR PRODUCT\nSub-4 m model-reconstructed target','VALIDATION\nPSNR / SSIM / SAM / ERGAS / RMSE','UNCERTAINTY\nReliability map','APPLICATIONS\nAgriculture / Urban / Disaster / Change','NEMOTRON\nReasoning / orchestration / reporting'];return <><Head eyebrow="SYSTEM OVERVIEW" title="TerraSR Architecture" subtitle="A simple, explainable route from observed satellite input to AI-assisted interpretation."/><section className="architecture">{nodes.map(x=><div key={x}>{x.split('\n').map(y=><p key={y}>{y}</p>)}</div>)}</section></>}
function Report({data,download}:{data:Any,download:(k:'json'|'csv')=>void}){return <><Head eyebrow="REPORT" title="TerraSR Scene Analysis Report" subtitle="A concise, portable summary of the selected-scene workflow."/><Panel className="report"><Badge>PROTOTYPE DEMONSTRATION</Badge><pre>{data.markdown||'Generating report…'}</pre><div className="actions"><button className="minor" onClick={()=>download('json')}>EXPORT JSON</button><button className="minor" onClick={()=>download('csv')}>EXPORT CSV</button></div></Panel></>}
function About(){return <><Head eyebrow="ABOUT" title="TerraSR" subtitle="Multispectral Earth Observation Super-Resolution Platform"/><section className="about">{[['Problem','Satellite imagery needs carefully explained fine-scale interpretation beyond 10 m observations.'],['Proposed Solution','Quality-aware multispectral reconstruction with validation, uncertainty and AI-assisted explanation.'],['Innovation','One coherent selected-scene workflow that keeps reconstruction distinct from direct observation.'],['Technology','FastAPI, React, Sentinel-2 L2A B02/B03/B04/B08, SwinIR integration point and NVIDIA Nemotron adapter.'],['Dataset Strategy','Deterministic, source-aligned offline demo scenes; optional Copernicus configuration remains backend-only.'],['Current Prototype Status','PROTOTYPE — deterministic enhancement, not trained model inference.'],['Production Roadmap','Paired HR/LR data → multispectral SwinIR training → benchmark evaluation → real uncertainty estimation → live Copernicus → production Nemotron orchestration.']].map(x=><Panel key={x[0]}><span className="label">{x[0]}</span><p>{x[1]}</p></Panel>)}</section></>}
function Modal({title,close,children,wide=false}:{title:string,close:()=>void,children:React.ReactNode,wide?:boolean}){return <div className="modalback" role="dialog"><section className={'modal '+(wide?'wide':'')}><button className="close" onClick={close}>×</button><span className="label">TERRASR</span><h2>{title}</h2>{children}</section></div>};createRoot(document.getElementById('root')!).render(<App/>);
